name: Update China List

on:
  schedule:
    - cron: '0 16 * * *'  # 每天北京时间午夜执行
  workflow_dispatch:

jobs:
  update-china-list:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Update China List
      run: |
        curl -o china-list.txt https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/china-list.txt
        sed -i 's/^/DOMAIN-SUFFIX,/' china-list.txt

    - name: Commit and Push Changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add china-list.txt
        git commit -m "Update China List"
        git push origin HEAD
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
