name: Update Rule List

on:
#  push:
#    branches:
#      - main
  workflow_dispatch:
  schedule:
    - cron: "30 22 * * *"

jobs:
  update-lists:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Update China List
      run: |
        DATE_COMMENT="Updated on: $(date -u +"%Y-%m-%d %H:%M:%S UTC")"
        curl -o china-list.txt https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/china-list.txt
        sed -i "1s|^|# $DATE_COMMENT\n|" china-list.txt
        sed -i '2,$ { s/^full:/DOMAIN,/; s/^regexp:/URL-REGEX,/; /^[^DOMAIN,URL-REGEX]/ s/^.*/DOMAIN-SUFFIX,&/ }' china-list.txt

    - name: Update Proxy List
      run: |
        DATE_COMMENT="Updated on: $(date -u +"%Y-%m-%d %H:%M:%S UTC")"
        curl -o proxy-list.txt https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/proxy-list.txt
        sed -i "1s|^|# $DATE_COMMENT\n|" proxy-list.txt
        sed -i '2,$ { s/^full:/DOMAIN,/; s/^regexp:/URL-REGEX,/; /^[^DOMAIN,URL-REGEX]/ s/^.*/DOMAIN-SUFFIX,&/ }' proxy-list.txt

    - name: Update Reject List
      run: |
        DATE_COMMENT="Updated on: $(date -u +"%Y-%m-%d %H:%M:%S UTC")"
        curl -o reject-list.txt https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/reject-list.txt
        sed -i "1s|^|# $DATE_COMMENT\n|" reject-list.txt
        sed -i '2,$ { s/^full:/DOMAIN,/; s/^regexp:/URL-REGEX,/; /^[^DOMAIN,URL-REGEX]/ s/^.*/DOMAIN-SUFFIX,&/ }' reject-list.txt

    - name: Commit and Push Changes
      run: |
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config user.name "github-actions[bot]"
        git add china-list.txt proxy-list.txt reject-list.txt
        git commit -m "Update Rule List"
        git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git main
