name: Update China List

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-lists:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Update Lists
      run: |
        # China List
        curl -o china-list.txt https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/china-list.txt
        sed -i 's/^/DOMAIN-SUFFIX,/' china-list.txt

        # Reject List
        curl -o reject-list.txt https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/reject-list.txt
        sed -i 's/^/DOMAIN-SUFFIX,/' reject-list.txt

        # Commit and push
        git config --global user.email "${{ secrets.GH_EMAIL }}"
        git config --global user.name "${{ secrets.GH_USERNAME }}"
        git add china-list.txt reject-list.txt
        git commit -m "Update Lists"
        git push origin main
        
