name: Update China List

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 时间 00:00 执行
  workflow_dispatch:  # 添加手动触发器

jobs:
  update-china-list:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Download china-list.txt
      run: |
        curl -s -O https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/china-list.txt

    - name: Process china-list.txt
      run: |
        sed -i 's/^/DOMAIN-SUFFIX,/' china-list.txt

    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Commit Changes
      run: |
        git add china-list.txt
        git commit -m "Update china-list.txt"

    - name: Push Changes
      run: |
        git push origin HEAD:main
