name: Update China List and Reject List

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-lists:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Update China List
      run: |
        curl -o china-list.txt https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/china-list.txt

    - name: Update Reject List
      run: |
        curl -o reject-list.txt https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/reject-list.txt

    - name: Add Prefix to Domain Lists and Update Timestamp
      run: |
        update_file() {
          file=$1
          if [[ $(head -n 1 "$file") == \#* ]]; then
            # If the first line is a comment, replace the comment with current date-time
            sed -i "1s/.*/# $(date '+%Y-%m-%d %H:%M:%S')/" "$file"
          else
            # If the first line is not a comment, add a new line with a comment and current date-time
            sed -i "1i# $(date '+%Y-%m-%d %H:%M:%S')\\n" "$file"
          fi
          # Add "DOMAIN-SUFFIX," prefix to each line
          sed -i 's/^/DOMAIN-SUFFIX,/' "$file"
        }

        update_file china-list.txt
        update_file reject-list.txt

    - name: Configure Git
      run: |
        git config --global user.email "${{ secrets.GH_EMAIL }}"
        git config --global user.name "${{ secrets.GH_USERNAME }}"

    - name: Commit and Push Changes
      run: |
        git add china-list.txt reject-list.txt
        git diff --quiet || git commit -m "Update China List and Reject List"
        git push origin main  # 或者你的主要分支
